### PR TITLE
drivers: rf: RFCC26X2_multiMode: fix power down/rat race

### PR DESCRIPTION
**Pull request by fgrandel**
The driver had a race condition that would systematically try to schedule the power down procedure while already powering down when a RAT timer was active during power down.

@vaishnavachath That's the one we talked about.

@reviewers: Vaishnav will try to upstream this fix to the TI connectivity team. If this is successful and a fix published upstream, I'll upgrade the driver so we avoid future merge conflicts. But as this is a blocker for TSCH (and any CC26xx network reference clock), I hope we can accept this change for Zephy until upstream has it.

Before:
image

The trace ends with a Bus Fault due to the RF domain being powered down already and the SWI handler trying to access the registers.

After:
image

### CODE REVIEW

**Comment by fgrandel** [comment]
@cfriedt @niflostancu Could one of you maybe do a second review?

**Review by cfriedt — APPROVED** [review]
LGTM

**Comment by cfriedt** [comment]
I've never tried SEGGER SystemView btw. @fgrandel - how do you find it?

I have used both the j-link and j-link mini with these devices (via OpenOCD) though.

**Comment by vaishnavachath** [comment]
Thanks a lot @fgrandel for the root cause analysis and fix.

**Review by vaishnavachath — APPROVED** [review]

**Comment by fgrandel** [comment]
> I've never tried SEGGER SystemView btw. @fgrandel - how do you find it?

I love it - it's easy to extend and use - and SEGGER's "friendly license" is ideal for non-commercial open source work IMO. Kudos to SEGGER!

**Pull request merged**
