### PR TITLE
cc13x2_cc26x2: update to TI SimpleLink SDK 4.40.04.04

### PR DESCRIPTION
**Pull request by niflostancu**
Update the HAL to TI SimpleLink SDK 4.40.
Retains Zephyr-specific patches.

Tested on both CC1352P LaunchXL and several custom-made CC1352R boards (using GPIO, timers and Sub-GHz radio).

Note: `PRCMPowerDomainStatus` was renamed to `PRCMPowerDomainsAllOn`, so the Zephyr drivers will require updating!
(I will come with an associated pull request on the main project)

Signed-off-by: Stancu Florin <niflostancu@gmail.com>

### CODE REVIEW

**Comment by cfriedt** [comment]
@niflostancu - I'm now a collaborator for TI platforms, so I should be able to merge this, assuming CI passes. Can you reopen a new PR for https://github.com/zephyrproject-rtos/zephyr/pull/38503?

**Comment by niflostancu** [comment]
Hello, 
This PR is not strictly required for power amplifier support (I have tested the patch without).
Check #28 instead ;) 

This is just to bring the SDK up to date (may have new features / bug fixes for TI CC13xx/26xx chips), so it's nice to have. The associated Zephyr PR was https://github.com/zephyrproject-rtos/zephyr/pull/38425, which I'll reopen right away.

**Comment by niflostancu** [comment]
BTW, I will come (next week) with revised Watchdog PR and new CC13xx ADC driver (I coded it a couple of months ago, need to port to pinctrl).
Possibly an upgrade to TI SDK version 6 (which is the latest) ;)

**Review by cfriedt — APPROVED** [review]
LGTM 👍

**Pull request merged**
