### PR TITLE
simplelink: ble: rf patch file

### PR DESCRIPTION
**Pull request by cfriedt**
Support for patching radio core for BLE

### CODE REVIEW

**Comment by cfriedt** [comment]
@bwitherspoon - this should allow the 15.4 driver to utilize the SimpleLink RF DriverLib API. It should be a relatively painless changeset (fingers crossed) and I'll see if @statropy can perform them.

**Comment by cfriedt** [comment]
CC @vanti

**Comment by cfriedt** [comment]
This is required for my BLE changes, and worked before the move to the 4.10 SDK.

**Comment by cfriedt** [comment]
Blocked by zephyrproject-rtos/zephyr#25416

**Comment by ioannisg** [comment]
@cfriedt I suggest you add a commit to the zephyrproject-rtos/zephyr#25416 PR that updates the west manifest entry for hal_ti repository, so we can have a CI run with the changes here.

**Comment by cfriedt** [comment]
Gah - didn't get to  zephyrproject-rtos/zephyr#25416 until after it was merged. Sorry, very busy week!

Will make a separate DNM pr to zephyr to run it through the regular zephyr CI environment.

**Comment by cfriedt** [comment]
Should be good to go since CI for the PR below is all green, @galak.
https://github.com/zephyrproject-rtos/zephyr/pull/26144

**Pull request merged**
