### PR TITLE
CC13x2x7 and CC26X2X7 support

### PR DESCRIPTION
**Pull request by jadonk**
I'm not looking for this to be merged, but BeagleConnect Freedom support depends on it, so it is at least needed to be in the repo such that I can update the west.yml for testing with the CI.

It would really help if @vaishnavachath would get this merged along with the rest of his CC1352P7 support.

### CODE REVIEW

**Review by cfriedt — CHANGES_REQUESTED** [review]
The accompanying PR needs to be green before this is merged.

Just putting a -1 here for safety, temporarily.

**Comment by cfriedt** [comment]
@stephanosio - can you please make sure that @vaishnavachath has reviewer privileges here and elsewhere?

**Comment by stephanosio** [comment]
> @stephanosio - can you please make sure that @vaishnavachath has reviewer privileges here and elsewhere?

Done. You will be add @vaishnavachath as a reviewer once he accepts the invitation.

Also, [`hal_ti` entry in the `MAINTAINERS.yml`](https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml#L2768) should be updated now that there is a TI platform maintainer.

**Comment by cfriedt** [comment]
@vaishnavachath, @jadonk - there is something wrong with the 'pthread_self` declaration. I'm not sure if it's new in this PR or what.

https://github.com/zephyrproject-rtos/zephyr/actions/runs/4458113413/jobs/7829701672#step:13:1459

We had a similar issue in hal/ti a while ago so I'll see if I can find the link.

**Comment by vaishnavachath** [comment]
@cfriedt @jadonk I have rebased the changes on top of the latest commit and the build errors are fixed, https://github.com/zephyrproject-rtos/zephyr/pull/55488/checks
Also there were two commits that was fixing changes in the first commit, since it did not add value to the commit history, I have squashed the commits.

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
